/**
 * generated by Xtext
 */
package org.xtext.example.domainmodel.validation;

import org.xtext.example.domainmodel.validation.AbstractDomainmodelValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DomainmodelValidator extends AbstractDomainmodelValidator {
}
