/*
* generated by Xtext
*/
package org.eclipse.xtext.common.types.xtext.ui.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class RefactoringTestLanguageProposalProvider extends org.eclipse.xtext.common.types.xtext.ui.ui.contentassist.AbstractRefactoringTestLanguageProposalProvider {

}
