/*
* generated by Xtext
*/
package org.xtext.example.domainmodel.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.domainmodel.services.DomainmodelGrammarAccess;

import com.google.inject.Inject;

public class DomainmodelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DomainmodelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.domainmodel.parser.antlr.internal.InternalDomainmodelParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.domainmodel.parser.antlr.internal.InternalDomainmodelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}
	
	public DomainmodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DomainmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
